### ISSUE TITLE
How to catch "Can't set headers after they are sent."

### ISSUE THREAD

**Issue by Bijoshtj** [expressjs/timeout#22]
Because of some implementation issue in my code i got the bug:

Possibly unhandled Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.header (/home/bijosh/Work/server_projects/my-sample-project/node_modules/express/lib/response.js:718:10)

there were a condition in code that im invoking response.status().json() multiple times which was causing the issue.
I am using winton logger module for logging.

On debugging I 've gone through 2 cases -

Test 1 (invoking res.json() 2 times in consecutive line):
res.status().json();
res.status().json();

Test 2 (invoking res.json() 2 times, but 2nd call is happening inside timeout callback with 0 timeout):
res.status().json();
setTimeout(function () {
  res.status().json();
}, 0);

In both cases, i got the above error, but in 1st case logger is not catching error, but in 2nd case logger is catching it.

Anyone have idea. Why!!

Also I wanted to know how to catch this error somewhere in express app.

Thank You.

**Comment by Bijoshtj** [comment]
I got the issue. I was using promise there. which was causing the problem.

**Comment by dougwilson** [comment]
Hi, sorry it took a while to get to your question, from a holiday :) I'm glad you were able to figure out the issue. If you still have questions or it still does not seem to be resolved, please let me know. Providing the full source code I could copy and paste and run would be ideal, otherwise it's hard to really answer the question :)
