### ISSUE TITLE
ServiceUnavailableError: Response timeout

### ISSUE THREAD

**Issue by Omar1123** [expressjs/timeout#27]
Hello

I defined the timeout as middleware as follows.

That way everything works fine but when you want to see the timeout message and define it as

```
App.use (timeout ('0s')); // To see the timeout error message

App.use (haltOnTimedout);

Function haltOnTimedout (req, res, next) {

    If (! Req.timeout) {
        //console.dir("Its here);
        Next ();
    } Else {
        Res.status (408) .json ({
            'Message': 'Timeout',
            'Status': '408',
            'Content': 'Timeout'
        });
    }
}
```

I get the following error

> ServiceUnavailableError: Response timeout
>     At IncomingMessage <anonymous> (C: \ Users \ Jake \ Desktop \ Projects \ RestApi \ Server \ Node js \ Solutions \ node-rest \ node_modules \ connect-timeout \ index.js: 84: 8)
>     At emitOne (events.js: 96: 13)
>     At IncomingMessage.emit (events.js: 188: 7)
>     At timeout._onTimeout (C: \ Users \ Jake \ Desktop \ Projects \ RestApi \ Server \ Node js \ Solutions \ node-rest \ node_modules \ connect-timeout \ index.js: 49:11)
>     At ontimeout (timers.js: 365: 14)
>     At tryOnTimeout (timers.js: 237: 5)
>     At Timer.listOnTimeout (timers.js: 207: 5)
> _http_outgoing.js: 356
>     Throw new Error ('Can \' t set headers after they are sent. ');

I'm doing something wrong, how can I check when a timeout happens?

**Comment by dougwilson** [comment]
Check the README... https://github.com/expressjs/timeout#express-3x and the multiple examples.

**Comment by mikeuduc** [comment]
@Omar1123 The problem is that connect-timeout will call next(err) if you do not pass {respond: false} in the options. This will cause the express router to skip all of your middleware(s) and to your error handler. - https://expressjs.com/en/guide/error-handling.html

To me, the documentation seems outdated (express v3) or incorrect because haltOnTimedout will never get called unless you pass {respond: false}, yet the example uses the default { respond: true } with haltOnTimedout as middleware. 

Putting it together, you can either pass { respond: false } and create your own error to pass to your error handler as follows:

```
function haltOnTimedout(req, res, next){
	if (!req.timedout){
		next();
	}
	else{
		let err = new Error("My custom timeout error");
		err.status = 504;
		next(err);
	}
}

function errorHandler( function(err, req, res, next) {
        //handle your timeout error here
        res.sendStatus(err.status)
});

router.post( '/upload', connectTimeout('1s', { respond: false } ), multipartMiddleware, haltOnTimedout, successHandler, errorHandler)
```

Or you can use default {respond: true} which will skip your haltOnTimedout middleware and process the error from connect-timeout

`
router.post( '/upload', connectTimeout('1s'), multipartMiddleware, successHandler, timedoutErrorHandler)
`
